// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBank.Contas.Data;

namespace MyBank.Contas.Data.Migrations
{
    [DbContext(typeof(ContasContext))]
    partial class ContasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyBank.Contas.Domain.ContaCorrente", b =>
                {
                    b.Property<string>("NumeroConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(5)");

                    b.Property<double>("Saldo")
                        .HasColumnType("double");

                    b.HasKey("NumeroConta");

                    b.ToTable("Contas");
                });
#pragma warning restore 612, 618
        }
    }
}
